AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - test/**/*
    - app/admin/**/*

Encoding:
  Enabled: false

Documentation:
  Enabled: false

RedundantSelf:
  Enabled: false

Blocks:
  Enabled: false

LineLength:
  Max: 90
