# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 628773be37e1fa96ae090f6c68a0062bbe5d4188671bdfa1020da65ed8fee02efee47b2fce2b0353f9fec34797b95082fbc109d3bee142ceb15e05996b9fe11e

test:
  secret_key_base: 59d4bae7a9a271649d41ab7eb6f4fa238fdb96c591e2dd24453b47a071671941c15d81e1b58ef3b42d2c5f0c2f905fd008c557fb9ddcb1cdf879c554cb6a48a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
